analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
