name: fibscli
description: Backgammon
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fibscli_lib:
    path: ../fibscli_lib
  cupertino_icons: ^1.0.1+1
  dartx: ^1.2.0
  shared_preferences: ^2.2.1
  syncfusion_flutter_datagrid: ^23.1.36
  trotter: ^2.0.0
  url_launcher: ^6.1.11
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fibsboard:
    path: ../fibsboard/

flutter:
  uses-material-design: true
