name: fibscli
description: Backgammon
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartx: ^0.5.0
  trotter: ^1.2.0
  shared_preferences: ^0.5.12
  device_preview: ^0.4.8
  fibscli_lib:
    path: ../fibscli_lib
  syncfusion_flutter_datagrid: ^18.3.35-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

