name: fibscli
description: Backgammon
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fibscli_lib:
    path: ../fibscli_lib
  cupertino_icons: ^1.0.1+1
  dartx: ^0.5.0
  shared_preferences: ^0.5.12
  syncfusion_flutter_datagrid: ^18.3.35-beta
  trotter: ^1.2.0
  web_socket_channel: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fibsboard:
    path: ../fibsboard/

flutter:
  uses-material-design: true
