part of 'cookie_monster.dart';

// ignore_for_file: constant_identifier_names, public_member_api_docs

enum FibsCookie {
  CLIP_NONE, // = 0
  CLIP_WELCOME, // = 1,
  CLIP_OWN_INFO, // = 2,
  CLIP_MOTD_BEGIN, // = 3,
  CLIP_MOTD_END, // = 4,
  CLIP_WHO_INFO, // = 5,
  CLIP_WHO_END, // = 6,
  CLIP_LOGIN, // = 7,
  CLIP_LOGOUT, // = 8,
  CLIP_MESSAGE, // = 9,
  CLIP_MESSAGE_DELIVERED, // = 10,
  CLIP_MESSAGE_SAVED, // = 11,
  CLIP_SAYS, // = 12,
  CLIP_SHOUTS, // = 13,
  CLIP_WHISPERS, // = 14,
  CLIP_KIBITZES, // = 15,
  CLIP_YOU_SAY, // = 16,
  CLIP_YOU_SHOUT, // = 17,
  CLIP_YOU_WHISPER, // = 18,
  CLIP_YOU_KIBITZ, // = 19,
  FIBS_PreLogin, // the ASCII "FIBS" art, etc.
  FIBS_LoginPrompt,
  FIBS_WARNINGAlreadyLoggedIn, // csells: already logged in warning
  FIBS_FailedLogin, // use this to detect a failed login (e.g. wrong password)
  FIBS_MOTD,
  FIBS_Goodbye,
  FIBS_PostGoodbye, // "send cookies", etc.
  FIBS_Unknown, // don't know the type, probably can ignore
  FIBS_Empty, // empty string
  FIBS_Junk, // a message we don't care about, but is not unknown
  FIBS_ClearScreen,
  FIBS_BAD_AcceptDouble, // DANGER! See notes in .c file about these 2 cookies!
  FIBS_Average,
  FIBS_DiceTest,
  FIBS_Stat,
  FIBS_Why,
  FIBS_NoInfo,
  FIBS_LastLogout,
  FIBS_RatingCalcStart,
  FIBS_RatingCalcInfo,
  FIBS_SettingsHeader,
  FIBS_PlayerListHeader,
  FIBS_AwayListHeader,
  FIBS_RatingExperience,
  FIBS_NotLoggedIn,
  FIBS_StillLoggedIn,
  FIBS_NoOneIsAway,
  FIBS_RatingsHeader,
  FIBS_IsPlayingWith,
  FIBS_Timeout,
  FIBS_UnknownCommand,
  FIBS_Username,
  FIBS_LastLogin,
  FIBS_YourLastLogin,
  FIBS_Registered,
  FIBS_ONEUSERNAME,
  FIBS_EnterUsername,
  FIBS_EnterPassword,
  FIBS_TypeInNo,
  FIBS_SavedScoreHeader,
  FIBS_NoSavedGames,
  FIBS_UsersHeardYou,
  FIBS_MessagesForYou,
  FIBS_IsAway,
  FIBS_OpponentLogsOut,
  FIBS_Waves,
  FIBS_WavesAgain,
  FIBS_YouGag,
  FIBS_YouUngag,
  FIBS_YouBlind,
  FIBS_YouUnblind,
  FIBS_WatchResign,
  FIBS_UseToggleReady,
  FIBS_WARNINGSavedMatch,
  FIBS_NoSavedMatch,
  FIBS_AlreadyPlaying,
  FIBS_DidntInvite,
  FIBS_WatchingHeader,
  FIBS_NotWatching,
  FIBS_NotWatchingPlaying,
  FIBS_NotPlaying,
  FIBS_PlayerNotPlaying,
  FIBS_NoUser,
  FIBS_CantInviteSelf,
  FIBS_CantWatch,
  FIBS_CantTalk,
  FIBS_CantBlindYourself,
  FIBS_CantGagYourself,
  FIBS_WontListen,
  FIBS_NoOne,
  FIBS_BadMove,
  FIBS_MustMove,
  FIBS_MustComeIn,
  FIBS_CantShout,
  FIBS_DontKnowUser,
  FIBS_MessageUsage,
  FIBS_Done,
  FIBS_SavedMatchesHeader,
  FIBS_NotYourTurnToRoll,
  FIBS_NotYourTurnToMove,
  FIBS_YourTurnToMove,
  FIBS_Ratings,
  FIBS_PlayerInfoStart,
  FIBS_EmailAddress,
  FIBS_NoEmail,
  FIBS_ListOfGames,
  FIBS_SavedMatch,
  FIBS_SavedMatchPlaying,
  FIBS_SavedMatchReady,
  FIBS_YouAreWatching,
  FIBS_YouStopWatching,
  FIBS_PlayerStartsWatching,
  FIBS_PlayerStopsWatching,
  FIBS_PlayerIsWatching,
  FIBS_ReportUnlimitedMatch,
  FIBS_ReportLimitedMatch,
  FIBS_RollOrDouble,
  FIBS_YouWinMatch,
  FIBS_PlayerWinsMatch,
  FIBS_YouReject,
  FIBS_YouResign,
  FIBS_ResumeMatchRequest,
  FIBS_ResumeMatchAck0,
  FIBS_ResumeMatchAck5,
  FIBS_NewMatchRequest,
  FIBS_UnlimitedInvite,
  FIBS_YouInvited,
  FIBS_NewMatchAck9,
  FIBS_NewMatchAck10,
  FIBS_NewMatchAck2,
  FIBS_YouTerminated,
  FIBS_OpponentLeftGame,
  FIBS_PlayerLeftGame,
  FIBS_PlayerRefusingGames,
  FIBS_TypeJoin,
  FIBS_ShowMovesStart,
  FIBS_ShowMovesWins,
  FIBS_ShowMovesRoll,
  FIBS_ShowMovesDoubles,
  FIBS_ShowMovesAccepts,
  FIBS_ShowMovesRejects,
  FIBS_ShowMovesOther,
  FIBS_Board,
  FIBS_YouRoll,
  FIBS_PlayerRolls,
  FIBS_PlayerMoves,
  FIBS_PlayerCantMove,
  FIBS_Doubles,
  FIBS_AcceptRejectDouble,
  FIBS_StartingNewGame,
  FIBS_PlayerAcceptsDouble,
  FIBS_YouAcceptDouble,
  FIBS_Turn,
  FIBS_FirstRoll,
  FIBS_DoublingCubeNow,
  FIBS_CantMove,
  FIBS_CantMoveFirstMove,
  FIBS_ResignRefused,
  FIBS_YouWinGame,
  FIBS_OnlyPossibleMove,
  FIBS_AcceptWins,
  FIBS_ResignWins,
  FIBS_ResignYouWin,
  FIBS_WatchGameWins,
  FIBS_ScoreUpdate,
  FIBS_MatchStart,
  FIBS_YouAcceptAndWin,
  FIBS_OnlyMove,
  FIBS_BearingOff,
  FIBS_PleaseMove,
  FIBS_MakesFirstMove,
  FIBS_YouDouble,
  FIBS_MatchLength,
  FIBS_PlayerWantsToResign,
  FIBS_PlayerWinsGame,
  FIBS_JoinNextGame,
  FIBS_ResumingUnlimitedMatch,
  FIBS_ResumingLimitedMatch,
  FIBS_PlayersStartingMatch,
  FIBS_PlayersStartingUnlimitedMatch,
  FIBS_MatchResult,
  FIBS_YouGiveUp,
  FIBS_PlayerIsWaitingForYou,
  FIBS_SettingsValue, // csells
  FIBS_SettingsChange, // csells
  FIBS_NotDoingAnything, // csells
}
