name = "fibs-proxy"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = true
routes = [
  { pattern = "proxy.playfibs.com", custom_domain = true },
]

[vars]
ENVIRONMENT = "dev"
VERSION = "local"
ALLOWED_ORIGINS = "http://127.0.0.1:18088,http://localhost:18088,http://127.0.0.1:8088,http://localhost:8088"

[[analytics_engine_datasets]]
binding = "FIBS_PROXY_ANALYTICS"
dataset = "fibs_proxy_events"
